### ISSUE TITLE
Error in the results provided by the result page

### ISSUE THREAD

**Issue by eun5young** [OSS-TeamProjectt/IT-MBTI#59]
I tested our project, and it was amazing! 😀

However, I discovered one issue. When I tested it, I selected "Strongly Agree" for all the questions. Despite this, the results did not show each type's percentage as 100%, as seen in the image below. It seems there might be an error in the part of the code that calculates the proportions for each type in the test results. 

![image](https://github.com/user-attachments/assets/42267b6c-0f4e-43e3-b105-fe6d7e3c8d7f)

**Comment by yuyoung924** [comment]
I checked and I think the combined result is 100% ㅠ I think we need to allocate 100% for each type..
