### ISSUE TITLE
Update Result Page Features and Fix Errors

### ISSUE THREAD

**Issue by han3o1** [OSS-TeamProjectt/IT-MBTI#67]
I will share the current situation of our project!

Modifications:
- [x] Modify the result page to allow users to view all tied results when multiple scores are the same.
- [x] Connect professor images to their corresponding external links.
- [x] Fix the percentage calculation errors in the result display.

Feel free to share any additional thoughts or suggestions on how to improve the result page further. 
Your feedback is highly valued and will help us make the user experience even better! 😊

**Comment by kimm00** [comment]
Thank you for sharing the updates on the result page! I would like to work on fixing the percentage calculation errors in the result display as it seems crucial for providing accurate results to users.

I'll review the related code and ensure that the calculations handle all tied results correctly. Once I make the changes, I'll submit a PR for further review. Let me know if you have any additional feedback or considerations for this task! 😊

**Comment by han3o1** [comment]
That's a good point! I'll reflect on that.
