### ISSUE TITLE
Graph Component: a problem of percentage is not displayed as 0

### ISSUE THREAD

**Issue by shinh09** [OSS-TeamProjectt/IT-MBTI#74]
The percentage should be marked 0 when there is no score in the Graph component, but the function is failing in the unit test.
<img width="333" alt="스크린샷 2024-12-16 오후 10 28 31" src="https://github.com/user-attachments/assets/ceb135b6-875a-4ee9-b2c2-ed46bc7a08cf" />
<img width="483" alt="스크린샷 2024-12-16 오후 10 28 44" src="https://github.com/user-attachments/assets/44d0a303-403c-4032-a125-0c3816bc5498" />

**Comment by han3o1** [comment]
I've tried several modifications but none of them worked well. ㅠㅠ
Here are my tests.
```
function Graph({ scores }) {
  const maxScorePerType = 30;
  const graphData = scores.map(([type, score]) => {
    const percentage = Math.round((score / maxScorePerType) * 100);
    return {
      label: type,
      percentage: percentage,
      color: fixedColors[type],
    };
  });
```
I think we need to modify it outside of the Graph.js file.

**Comment by han3o1** [comment]
![image](https://github.com/user-attachments/assets/f15a034a-aeca-46c6-9950-497efd803f16)
Now I resolves an issue of percentage calculations!!
```
return (
    <QuestionContainer>
      <QuestionText>{questionText}</QuestionText>
      <OptionsContainer>
      <OptionButton $isSelected={selectedOption === 1} onClick={() => handleClick(0)}>
        Strongly Disagree
      </OptionButton>
      <OptionButton $isSelected={selectedOption === 2} onClick={() => handleClick(2.5)}>
        Disagree
      </OptionButton>
      <OptionButton $isSelected={selectedOption === 3} onClick={() => handleClick(5)}>
        Neutral
      </OptionButton>
      <OptionButton $isSelected={selectedOption === 4} onClick={() => handleClick(7.5)}>
        Agree
      </OptionButton>
      <OptionButton $isSelected={selectedOption === 5} onClick={() => handleClick(10)}>
        Strongly Agree
      </OptionButton>
      </OptionsContainer>
    </QuestionContainer>
  );
```
Please refer to the code!

**Comment by yuyoung924** [comment]
Oh, good job! I think we only need to pass the unit test!
